### ISSUE TITLE
backup_configuration.binary_log_enabled is always set to true in TFState even after changing to false

### ISSUE THREAD

**Issue by syedrakib** [terraform-google-modules/terraform-google-sql-db#102]
I spinned up ClousSQLMysQL with `backup_configuration.binary_log_enabled` set to `true`. Now i am trying to set it to `false`.

---

The `terraform plan` said:

            backup_configuration {
              ~ binary_log_enabled = true -> false
                enabled            = false
                start_time         = "00:05"
            }

---

The `terraform apply` was successful saying

    Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

---

However, when i plan and apply again, it is again saying the same things as if the previous changes were not performed.

---

I also looked into the TFState file and it shows the following even though the `plan-apply` steps said it changed `backup_configuration.binary_log_enabled` to `false` successfully

    "backup_configuration": [
        {
            "binary_log_enabled": true,
            "enabled": false,
            "location": "",
            "start_time": "00:05"
        }
    ],

**Comment by morgante** [comment]
This sounds like a provider bug, please file there.
