### ISSUE TITLE
is there support for creating multipe postgresql schema 

### ISSUE THREAD

**Issue by mhamaydeh** [terraform-google-modules/terraform-google-sql-db#105]
we have a case that we need to create postgresql cloud sql , with multiple schema . since we are creating the database with private ip , we can't use `provider "postgresql"`  

what is the best solution to do that while using the terraform-google-sql-db

**Comment by morgante** [comment]
This doesn't seem related to the module itself, as it focuses on creating the database not applying schemas.

I'd recommend running your Terraform apply from within your VPC to be able to use the postgres provider.
