### ISSUE TITLE
Failing import instance

### ISSUE THREAD

**Issue by tahsinrahman** [terraform-google-modules/terraform-google-sql-db#106]
I'm trying to import an existing cloud sql instance, but it is failing with invalid credentials

```
$ terraform import module.dev_infra.module.mysql_db.module.google_mysql_db.google_sql_database_instance.default projects/<project-id>/instances/<instance-name>
```
```
Error: Error reading SQL Database Instance "<instance-name>": googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
More details:
Reason: authError, Message: Invalid Credentials
```

**Comment by syedrakib** [comment]
@tahsinrahman i am facing this same issue today. Any resolution?

**Comment by zs-codex** [comment]
We experience this too:
```
Error: Error waiting for Create Instance: error while retrieving operation: googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
More details:
Reason: authError, Message: Invalid Credentials
```

It seems to only occur when we provision `google_sql_database_instance` resource. I've tried playing around with permissions but that doesn't seem to be the issue. In fact, the SQL db seems to be created even if the failure above occurs.

**Comment by tahsinrahman** [comment]
@zs-codex try running terraform refresh. It worked for us

**Comment by zs-codex** [comment]
> @zs-codex try running terraform refresh. It worked for us

@tahsinrahman This happens on a "clean" deployment when no existing resources exist in the project - so I wouldn't expect this to happen unless there's some sort of race condition...

**Comment by syedrakib** [comment]
The matter of "taking time to provision" happens during first time creation of a resource - or even during modification of a resources- if the creation (or modificaiton) takes that length of time which goes beyond the expiry of access token.

But the matter of `authError, Message: Invalid Credentials` is not an error faced ONLY while provisioning (or modifying) resources for that long. There are cases where this error is faced before the provision API call is even made.

For those cases, we did see that the `terraform refresh` solved the problem.

**Comment by cbeltrame-minted** [comment]
Awesome, `terraform refresh` solved the problem here too, thanks a lot
