### ISSUE TITLE
Output variable for additional_users generated passwords

### ISSUE THREAD

**Issue by tfluehmann** [terraform-google-modules/terraform-google-sql-db#115]
Is there already a way to output the passwords for the additional_users?
I am creating several databases with this terraform module which works great. In as second step I create additional_users for those databases, but finally I cannot get the passwords of those users to use them further.

**Comment by morgante** [comment]
The `generated_user_password` output exposes this.

Note that (currently) all users will initially have the *same* generated password.

**Comment by tfluehmann** [comment]
Oh cool, didn't realize that it's the default password.
Thanks for the quick answer!
