### ISSUE TITLE
Change cloud SQL postgres machine type (tier)

### ISSUE THREAD

**Issue by mhamaydeh** [terraform-google-modules/terraform-google-sql-db#119]
Hello , 
I have created cloud PostgreSQL instance on GCP  using the modules , at the creation time i was using database tier `db-custom-2-7680` and now i need to change it to `db-custom-4-15360`

when I run Terraform apply it does not recognize the change of the database tier , 

what could be the problem and how to solve that . 

Thanks

**Comment by morgante** [comment]
You can run `terraform destroy` to delete the old database.

**Comment by dxs516** [comment]
@morgante : Do we have to destroy the DB? Can't it be upgraded without losing data.

**Comment by morgante** [comment]
@dxs516 It should be possible to upgrade in place as well. Simply change the `tier` variable.

**Comment by st250467** [comment]
hi i am facing same issue... like i have postgresql with replica... but it is not updating tier due to replica. it says- "master instance can not be larger than read replica".  How we can update tier using terrfaorm?
