### ISSUE TITLE
How to set innodb_file_per_table flag for MySQL 

### ISSUE THREAD

**Issue by syedrakib** [terraform-google-modules/terraform-google-sql-db#124]
Following this doc https://cloud.google.com/sql/faq#reclaimingspace i want to set the `innodb_file_per_table` flag for my MySQL instance provisioned with this TF module.

Where/How can I set it?

**Comment by bharathkkb** [comment]
Hi @syedrakib 
I believe should be able to set it via the [`database_flags` variable. ](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/295ca1842b4bd4121b0618fedf773c7e5363f40a/modules/mysql/variables.tf#L118)
Could you try something like
```tf
module "sql-db" {
.
.
database_flags = [{ name = "innodb_file_per_table", value ="on" }]
.
}
```

**Comment by syedrakib** [comment]
that's the variable i was looking for... thanks.... i will give it a try.
