### ISSUE TITLE
random_instance_name doesn't work in postgres module

### ISSUE THREAD

**Issue by debek** [terraform-google-modules/terraform-google-sql-db#129]
When I set source remotly:
```
module "airflow_cloud_sql" {
  source           = "GoogleCloudPlatform/sql-db/google//modules/postgresql"
```
This variable doesn't work.

It works only when the module is local:
```
module "postgresql-db" {
  source               = "../../modules/postgresql
```

**Comment by bharathkkb** [comment]
Hi @debek 

We have not done the `4.0` release which will include this feature. For tracking: https://github.com/terraform-google-modules/terraform-google-sql-db/pull/110

**Comment by debek** [comment]
Thank you.
