### ISSUE TITLE
missing connection_name in output

### ISSUE THREAD

**Issue by messiahUA** [terraform-google-modules/terraform-google-sql-db#13]
I want to use connection_name for cloud_sql_proxy, but this module doesn't output this basic value

**Comment by danisla** [comment]
The [example](https://github.com/GoogleCloudPlatform/terraform-google-sql-db/blob/master/examples/mysql-and-postgres/main.tf#L98) shows how to construct the connection name, we should definitely make this an output variable of the module.

**Comment by aaron-lane** [comment]
Fixed by #21.
