### ISSUE TITLE
Upgrading terraform version to v0.13.0

### ISSUE THREAD

**Issue by syedrakib** [terraform-google-modules/terraform-google-sql-db#136]
I was not able to upgrade my IAC terraform to v0.13.0. because i am using this `Google-SQL-DB/MySQL` submodule which has a version constraint on `"~> 0.12.6"`

https://github.com/terraform-google-modules/terraform-google-sql-db/blob/2a0a14246c10d1a3985e4e2edda897f637e77ce7/modules/mysql/versions.tf#L18

Are the any current plans in place already for upgrading its version? If not, i will try to create a PR for it.

**Comment by morgante** [comment]
If you can test it with Terraform 0.13 please do feel free to file a PR. Example: https://github.com/terraform-google-modules/terraform-google-network/pull/197

**Comment by morgante** [comment]
Fixed by #135.
