### ISSUE TITLE
Can't converge mysql-hq example

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-sql-db#137]
There's an error in this test:

`
$$$$$$ Running command `terraform apply -lock=true -lock-timeout=0s -input=false -auto-approve=true -no-color -parallelism=10 -refresh=true  ` in directory /workspace/test/fixtures/mysql-ha
       
       Error: Invalid forEach argument
       
       The "for_each" value depends on resource attributes that cannot be determined
       until apply, so Terraform cannot predict how many instances will be created.
       To work around this, use the -target argument to first apply only the
       resources that the for_each depends on.
```

**Comment by fenglyu** [comment]
I have the same problem here.
```

Error: Invalid for_each argument

  on ../terraform-google-sql-db/modules/postgresql/read_replica.tf line 24, in resource "google_sql_database_instance" "replicas":
  24:   for_each             = local.replicas

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.

```

**Comment by Dev25** [comment]
Hmm the read replica resource already depends on the master instance resource (since its required field), however the key/name for the replica depends on the `random_id` resource. I'll make a quick PR to see if that fixes CI.

```tf
 master_instance_name = var.random_instance_name ? "${var.name}-${random_id.suffix[0].hex}" : var.name
 replicas = {
    for x in var.read_replicas : "${local.master_instance_name}-replica${var.read_replica_name_suffix}${x.name}" => x
  }

**Comment by Dev25** [comment]
So i can confirm the problem is related with ^ when `random_instance_name = true`

**Comment by Dev25** [comment]
So i've been able to workaround the problem locally by simpliyfing the state key to just be `for x in var.read_replicas : x.name => x`

https://github.com/terraform-google-modules/terraform-google-sql-db/pull/121/files#r439883647
Introduced the dependancy on using the master instance name for a easier migration path/script.

Could either add a workaround and keep the same state key or tweak the migration script and anyone recently vendoring master will need to manually migrate their own state.


cc @morgante

**Comment by morgante** [comment]
Got it, I think we should probably just use `x.name` and tweak the migration scripts. Anyone on master would have to manually migrate if they were impacted by this.

**Comment by Dev25** [comment]
Sounds reasonable, i'm fairly busy atm to properly test so if someone could pick this up that would be great.

If i recall, you can't just set `x.name` to be the full instance name (to satisfy the state migration, since it only sees the properties in the state file) because the instance name is partially based on `x.name`. You could add a flag to make it equal `x.name` but then its adding yet another required object field, that might be simpler overall though.

```tf
name = "${local.master_instance_name}-replica${var.read_replica_name_suffix}${each.value.name}"
```

**Comment by morgante** [comment]
Maybe it would be sufficient to drop the random part from the key?

I'm comfortable saying people using the random suffix will have to manually migrate their state file.

**Comment by Dev25** [comment]
That should work, random feature still hasn't been released yet so small % usage too.

**Comment by morgante** [comment]
@Dev25 Huge thanks for fixing this. I've been swamped and didn't realize it would be such a simple fix. :)
