### ISSUE TITLE
Credentials from provider

### ISSUE THREAD

**Issue by PCatinean** [terraform-google-modules/terraform-google-sql-db#145]
It seems while other modules can make use of the provider configuration to access the API sql-db relies on environment variables to find the credentials file.

**Comment by morgante** [comment]
Can you clarify the issue you're encountering? If you configure the google provider this module will use that config.

**Comment by PCatinean** [comment]
Hi @morgante, I get `Attempted to load application default credentials since neither `credentials` nor `access_token` was set in the provider block.  No credentials loaded.`. But in my provider block I use `credentials = file(var.credentials_file)`. Granted I call a module which in turn it calls the google-sql module. From my understanding it should inherit the provider nonetheless?

**Comment by morgante** [comment]
Make sure you have provider blocks for *both* `google` and the `google-beta` providers.

**Comment by PCatinean** [comment]
You are completely right, that's the explanation of why one module worked but the other was not (i should pay more attention to the documentation) . Thank you for your guidance and I apologize for the noise created :disappointed:
