### ISSUE TITLE
Cant update disk size

### ISSUE THREAD

**Issue by sumeetoc** [terraform-google-modules/terraform-google-sql-db#148]
Hi,

We are unable to update the disk size for MySQL instance using the [mysql terraform module](https://github.com/terraform-google-modules/terraform-google-sql-db/tree/master/modules/mysql), upon further inspection, I found that the [disk_size](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/ebdb1b743a722a43766149b78c6237f8055a4ff1/modules/mysql/main.tf#L107) variable is ignored in the Terraform lifecycle. 

Would like to understand the purpose or how to update the disk size of an instance using this module?

P.S: I also found the similar lifecycle rule in [Postgres terraform module](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/ebdb1b743a722a43766149b78c6237f8055a4ff1/modules/postgresql/main.tf#L102) as well

Thanks!

**Comment by morgante** [comment]
We ignore the disk_size changes because it would cause drift with Cloud SQL's native auto-resize functionality: https://github.com/terraform-google-modules/terraform-google-sql-db/pull/18

**Comment by sumeetoc** [comment]
That makes sense, thanks for providing the information. I opened a PR #149, which adds a note on this so that it's clear for others

**Comment by andreykaipov** [comment]
Just ran into this. Was confused for a sec why the disk size change wasn't showing up in our plans.

One of the [new features of Terraform v0.15.4](https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md#0154-may-19-2021) is to distinguish changes made outside of Terraform:

> **Noting changes made outside of Terraform**: Terraform has always, by default, made a point during the planning operation of reading the current state of remote objects in order to detect any changes made outside of Terraform, to make sure the plan will take those into account.
>
> Terraform will now report those detected changes as part of the plan result, in order to give additional context about the planned changes. We've often heard that people find it confusing when a plan includes a change that doesn't seem to be prompted by any recent change in the configuration, and so this feature is aiming to provide the previously-missing explanation for situations where Terraform is planning to undo a change.

Perhaps unignoring explicit disk resizes can be revisited? While there's nothing stopping configuration drift, it's now possible to distinguish when it happens, and wouldn't restrict a user's ability to resize the disks themselves.

**Comment by morgante** [comment]
While the new functionality definitely makes it clearer, I don't think it resolves the original problem (Terraform and CloudSQL fighting over the disk size).
