### ISSUE TITLE
issue disabling deletion_protection

### ISSUE THREAD

**Issue by davem-git** [terraform-google-modules/terraform-google-sql-db#154]
I'm using the module as in the example 

```
module "postgres" {
  source  = "GoogleCloudPlatform/sql-db/google//modules/postgresql"
  version = "= 4.1.0"
```
delete protection is enabled by default. There doesn't seem to be away to disable that

```
in module "postgres":
   4:   deletion_protection = var.deletion_protection

An argument named "deletion_protection" is not expected here.
```
so far the only way i've been able to delete an instance is by manually editing the state file to force and running a terraform delete.

am i using the module wrong? is this a feature that needs to be added? I'm confused as to how people are using this without the ability to delete it

**Comment by WillRemesh** [comment]
It looks like this was added for default instances but not for replicas. I created a PR to add a variable for replica instances here: https://github.com/terraform-google-modules/terraform-google-sql-db/pull/155

**Comment by WillRemesh** [comment]
This should be fully working in #155. Let me know if you have any other issues?

**Comment by davem-git** [comment]
awesome! I'll test it out. is it in a new version tag yet?
