### ISSUE TITLE
Allow multiple google_compute_global_address per VPC

### ISSUE THREAD

**Issue by odise** [terraform-google-modules/terraform-google-sql-db#159]
I ran into problems while trying to attach multiple mssql cluster to the same VPC. 

```
Error: Error creating GlobalAddress: googleapi: Error 409: The resource 'projects/********************/global/addresses/google-managed-services-dev-vpc' already exists, alreadyExists

  on .terraform/modules/sql.private_service_access/modules/private_service_access/main.tf line 27, in resource "google_compute_global_address" "google-managed-services-range":
  27: resource "google_compute_global_address" "google-managed-services-range" {
```

#158 should fix this. The `suffix` parameter could be a `random_id` or something else.

**Comment by morgante** [comment]
@odise Can you clarify what you're trying to accomplish? A single private service connection should actually be sufficient for multiple CloudSQL clusters.

**Comment by odise** [comment]
@morgante I would like to add an additional IP range to the private service connection which has been already created by the `private_service_access` module. My previous attempts failed when adding a new mssql instance using the existing one:

```
Failed to create subnetwork. Couldn't find free blocks in allocated IP ranges. Please allocate new ranges for this service provider.
```

Creating an additional `google_compute_global_address` resource should exactly accomplish that. However the name of that resource is already taken (see the error in the description). Maybe the `google_service_networking_connection` resource shouldn't be recreated in that case?

**Comment by odise** [comment]
After investigating quite a bit I found that #158 is not necessary in order to setup multiple Cloud SQL instances attached to the same VPC. Sorry for the inconvenience.
