### ISSUE TITLE
 replication_type = "SYNCHRONOUS" drift persistent after apply 

### ISSUE THREAD

**Issue by davem-git** [terraform-google-modules/terraform-google-sql-db#168]
```
  source  = "GoogleCloudPlatform/sql-db/google//modules/postgresql"
  version = "= 4.4.0"
```
using the latest version of the postgres module its seemed to introduced drift, I'm unsure how to fix it 
every plan comes back with this change

``` ~ settings {
            activation_policy           = "ALWAYS"
            authorized_gae_applications = []
            availability_type           = "REGIONAL"
            crash_safe_replication      = false
            disk_autoresize             = true
            disk_size                   = 10
            disk_type                   = "PD_SSD"
            pricing_plan                = "PER_USE"
          + replication_type            = "SYNCHRONOUS"
            tier                        = "db-custom-1-3840"
            user_labels                 = {}
            version                     = 5
```
replication type trying to set to  "SYNCHRONOUS" the apply runs cleanly, then the plan shows the same drift.

HA is enabled, however we don't have any read replicas. 

let me know if you need any more information.

**Comment by davem-git** [comment]
nevermind it seems to resolve it self. maybe it takes a bit after initialization?

**Comment by xylene314** [comment]
@davem-git i too get the same info every time my plan is running. Can i know , how the same was solved for you ?

**Comment by davem-git** [comment]
i don't think we did anything it went away after some time. are you having the same issue in multiple regions?

**Comment by davem-git** [comment]
hmm or maybe it didn't i might still see the drift again :(

**Comment by davem-git** [comment]
seems to be something with my local environment a coworker runs it and its clean, mine show this change

**Comment by davem-git** [comment]
ok i made sure had the lated, pull \ fetch verified my terraform versions, and deleted rm -rf.terraform then it ran clean

**Comment by xylene314** [comment]
@davem-git I added the below snippet to solve the error:

```
  lifecycle {
     ignore_changes = [settings[0].replication_type]
  }
```

**Comment by davem-git** [comment]
good to know. using 0.13.5

**Comment by PCatinean** [comment]
Even though this is a closed issue for me it kept showing even if I was using the latest version for the provider and the module. The only fix seems to have been `read_replicas = []` even though the documentation says it's the default.

**Comment by tomchinery** [comment]
I have also encountered this with both `read_replicas = []` and 
```
  lifecycle {
     ignore_changes = [settings[0].replication_type]
  }
```

In particular the `lifecycle` one doesn't seem to work with 0.13.5 with the message ```The block type name "lifecycle" is reserved for use by Terraform in a future
version.```

I'll be bumping to 0.14.4 soon maybe that will sort it for us.
