### ISSUE TITLE
postgres issues

### ISSUE THREAD

**Issue by sagivle** [terraform-google-modules/terraform-google-sql-db#17]
hi 
found 2 issues in postgres
1. terraform always  add the user even if it exist (i thing its because of the host:  "%" ) unlike the mysql
2. terraform output shows the password unlike the mysql

**Comment by namusyaka** [comment]
@sagivle Hi Sagiv, we have published new version [v1.1.0](https://github.com/GoogleCloudPlatform/terraform-google-sql-db/releases/tag/1.1.0) including our big progress (#21) .
Could you try to use it?
Please explain more details if you still have issues.

**Comment by aaron-lane** [comment]
@sagivle please reopen this issue if v1.1.0 did not address your concerns.
