### ISSUE TITLE
availability_type should be REGIONAL or ZONAL, not null

### ISSUE THREAD

**Issue by czka** [terraform-google-modules/terraform-google-sql-db#173]
This module advertises options `REGIONAL` or `null` for `availability_type` - https://github.com/terraform-google-modules/terraform-google-sql-db/blob/master/modules/mysql/variables.tf#L65:
>   description = "The availability type for the master instance. Can be either `REGIONAL` or `null`."

This seems bogus, because:
- Google advertises `REGIONAL` or `ZONAL` in their `gcloud` reference - https://cloud.google.com/sdk/gcloud/reference/sql/instances/create#--availability-type:
> _`AVAILABILITY_TYPE`_ must be one of:
> 
> **`regional`**
>     Provides high availability and is recommended for production instances; instance automatically fails over to another zone within your selected region.
>
> **`zonal`**
>     Provides no failover capability. This is the default.

- Google Terraform provider also advertises `REGIONAL` or `ZONAL` - https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#availability_type:
>  high availability (REGIONAL) or single zone (ZONAL)

**Comment by OscarVanL** [comment]
I think this is still an issue

If I want ZONAL do I set ZONAL or null? It's still unclear.
