### ISSUE TITLE
"deletion_protection" is not expected here.

### ISSUE THREAD

**Issue by luizm** [terraform-google-modules/terraform-google-sql-db#174]
Hi there.. I'm using the latest module version, and now I get this error when I tried to create a new SQL postgres

```
An argument named "deletion_protection" is not expected here
```

I've checked the module, and the usage seems right..

**Comment by morgante** [comment]
Make sure you're also using the latest version of the Terraform provider.

**Comment by luizm** [comment]
> Make sure you're also using the latest version of the Terraform provider.

sure, in this case, I'm using these versions: 
```
- Installing hashicorp/google v3.51.0...
- Installed hashicorp/google v3.51.0 (signed by HashiCorp)
- Installing hashicorp/google-beta v3.42.0...
- Installed hashicorp/google-beta v3.42.0 (signed by HashiCorp)
```

**Comment by morgante** [comment]
Can you upgrade the `google-beta` provider to v3.51 and see if the issue persists?

**Comment by luizm** [comment]
its works, thanks you @morgante
