### ISSUE TITLE
'Required attribute is not set' in Private Services Access module.

### ISSUE THREAD

**Issue by philipwigg** [terraform-google-modules/terraform-google-sql-db#176]
If I use the Private Service Access module with an empty state (network does not exist) then I can't run a plan or apply.

```
Error: Required attribute is not set

  on .terraform/modules/private-service-access/modules/private_service_access/main.tf line 43, in resource "google_service_networking_connection" "private_service_access":
  43:   network                 = data.google_compute_network.main.self_link
```

The issue seems to be that the module requires the network to already exist before a plan will run because of this data source:-.

https://github.com/terraform-google-modules/terraform-google-sql-db/blob/5765a5f8acfb6154e32c6c75f1ee3718b20d2f76/modules/private_service_access/main.tf#L17-L21

I think the data source has been added so that we have a user-friendly way to convert a network name into a self_link which is required by `google_compute_global_address` and `google_service_networking_connection` resources.

However, this breaks the module for people without an existing network so it might be better to either ask the users to supply a self_link themselves (probably easier) or derive it from the region, project and name.

Happy to send a PR but I'd like thoughts on the approach first.

**Comment by bharathkkb** [comment]
Hi @philipwigg 
What value are you passing in for `vpc_network`? If it is not a computed attribute Terraform may try to read during plan time instead of apply time.

**Comment by philipwigg** [comment]
Hi @bharathkkb and thanks for looking at this.

I created a small test case here - https://github.com/philipwigg/terraform-google-sql-db-176

Yes, the value for `vpc_network` is a computed value as per this test case.

**Comment by philipwigg** [comment]
I should add that in my test case, if I do a targeted apply (`terraform apply -target module.vpc`) so that the VPC network is created then the subsequent `terraform plan` works fine.

**Comment by bharathkkb** [comment]
@philipwigg that SGTM. Looks like this was introduced as a workaround https://github.com/terraform-google-modules/terraform-google-sql-db/pull/61 for the 2.x provider so we should ensure that it works as intended in the 3.x provider.

**Comment by mmllc-jsilverman** [comment]
I had this issue but I found that as a workaround, one can add "depends_on" to the module call. A simple workaround for this team would be to add this recommendation to the docs for this module.

For example (where new-network is being created by the module "terraform-google-modules/network/google")

`module "private-service-access-new-network" {
  source  = "GoogleCloudPlatform/sql-db/google//modules/private_service_access"
  project_id  = var.project_id
  vpc_network = "new-network"
  depends_on = [
    module.new-network,
  ]
}
`
