### ISSUE TITLE
MySQL v3.2.0 works with Terraform 13.x

### ISSUE THREAD

**Issue by coofercat** [terraform-google-modules/terraform-google-sql-db#183]
The MySQL module at version 3.2.0 has a `versions.tf` which forbids Terraform > 12. This is a shame because it seems to work fine with Terraform 13 too.

I realise the 4.x.x track is where TF 13 users are intended to go, but right now there's a fairly significant amount of change between the 3.x.x and 4.x.x branches, and there is no doco on how to manage the code transition.

Could we make a 3.2.1 tag which allows TF 0.13.x? It would separate the upgrades of TF 12 to 13 and 3.x.x and 4.x.x of this module.

**Comment by morgante** [comment]
We're not making new releases on the 3.x.x branch.

We recommend upgrading to 4.x.x. There is a doc explaining the changes: https://github.com/terraform-google-modules/terraform-google-sql-db/blob/master/docs/upgrading_to_sql_db_4.0.0.md
