### ISSUE TITLE
Allow additonal users to change TYPE for authentication methods

### ISSUE THREAD

**Issue by jrowinski3d** [terraform-google-modules/terraform-google-sql-db#186]
As the terraform resource suggests:
```
resource "google_sql_user" "users" {
  name     = "me"
  instance = google_sql_database_instance.master.name
  type     = "CLOUD_IAM_USER"
}
```

You can specify a **type** to enable IAM permissions if necessary. Would be useful to allow already configured users to authenticate with their google accounts. This would also enable proper tracing of who is actually logging in and modify/selecting/deleting things in the resultant database

**Comment by NightmareCinema** [comment]
Is there any plan on implementing this?

**Comment by morgante** [comment]
It seems like a good addition and we would be happy to review a pull request.

**Comment by eahrend** [comment]
@morgante created PR https://github.com/terraform-google-modules/terraform-google-sql-db/pull/237 to add this feature.
