### ISSUE TITLE
Create DNS records for replica instances

### ISSUE THREAD

**Issue by vgomenyuk** [terraform-google-modules/terraform-google-sql-db#187]
Hello.

I need to create DNS records for replica instances. I need to get `name` and `IP adress` for each replica. I want to use the data from outputs:
```
output "replicas_instance_first_ip_addresses" {
  value       = concat([for r in google_sql_database_instance.replicas : r.ip_address], [""])
  description = "The first IPv4 addresses of the addresses assigned for the replica instances"
}

output "replicas_instance_connection_names" {
  value       = concat([for r in google_sql_database_instance.replicas : r.connection_name], [""])
  description = "The connection names of the replica instances to be used in connection strings"
}
```

Then create a DNS record by using `for_each`.
But I can't find a proper way how to use concatenated output value of `replicas_instance_connection_names` and `replicas_instance_first_ip_addresses`.

Any ideas how to implement that? Much appreciate for the help.

**Comment by vgomenyuk** [comment]
The problem is actual, no answers yet.

**Comment by morgante** [comment]
@vgomenyuk What's the issue with using the outputs?

**Comment by vgomenyuk** [comment]
Outputs are not working or don't know the way how to use them in a working way. The problem: with having couple of replicas, we have to create a DNS name for each replica. And I suppose it should be done by using for_each somehow. But I haven't found the correct approach.

**Comment by morgante** [comment]
This tutorial might help you to learn more about for_each: https://www.terraform.io/docs/language/meta-arguments/for_each.html

**Comment by vgomenyuk** [comment]
I used it during my trying to find a working solution.
