### ISSUE TITLE
Read replica outputs contain junk empty string

### ISSUE THREAD

**Issue by andreykaipov** [terraform-google-modules/terraform-google-sql-db#192]
What's the purpose of the adding the empty string to the output list? For example, across all of the modules, we'll find the following outputs:

```terraform
// Replicas
output "replicas_instance_first_ip_addresses" {
  value       = concat([for r in google_sql_database_instance.replicas : r.ip_address], [""])
  description = "The first IPv4 addresses of the addresses assigned for the replica instances"
}

...

output "read_replica_instance_names" {
  value       = concat([for r in google_sql_database_instance.replicas : r.name], [""])
  description = "The instance names for the read replica instances"
}
```

However, something like the following is not only cleaner but more appropriate because our list has length zero when there are no replicas:

```terraform
[for r in google_sql_database_instance.replicas : r.name]
```

---

Furthermore (and probably better as its own issue), but as of TF 12 outputting entire resources is supported, so why not just do that instead of outputting only specific attributes? In my case I wanted to get the private IPs of my replicas, in which case we have to use a data source to look up each replica:

```terraform
module "mysql" {
  source  = "GoogleCloudPlatform/sql-db/google//modules/mysql"
  version = "4.4.0"
  ...
}

data "google_sql_database_instance" "replicas" {
  for_each = toset([for x in module.mysql.read_replica_instance_names : x if x != ""])
  name     = each.value
  project  = var.project_id
}

output "private_ips" {
  value       = [for x in data.google_sql_database_instance.replicas : x.private_ip_address]
}
```

The conditional to get rid of the empty string is an eyesore, and the data source approach is also quite roundabout when ideally the module could instead output the replicas it already knows about:

```terraform
// within the module
output "replicas" {
  value       = google_sql_database_instance.replicas
  description = "The read replicas"
}
```

Then the user can access any attributes they want without an intermediary data source:

```terraform
module "mysql" {
  source  = "GoogleCloudPlatform/sql-db/google//modules/mysql"
  version = "4.4.0"
  ...
}

output "private_ips" {
  value = [for x in module.mysql.replicas : x.private_ip_address]
}
```

**Comment by morgante** [comment]
I believe this was added as part of the transition to using `for_each` to work around some bugs in outputs, but we could remove it now. I'd be happy to review a PR.

**Comment by Dev25** [comment]
Indeed that workaround would of been due to a bug, cant recall the exact specifics right now but a quick search shows its also being used in the GKE module (list of node pool names etc)

Agree with outputting the replica resource itself, the old output formats were kept as is to maintain backwards compatibility during the for_each PR.

**Comment by andreykaipov** [comment]
Awesome! Thanks for the quick response! I'll create a PR right now

**Comment by andreykaipov** [comment]
The associated PR for this issue was #194 which was merged in, but I originally also elaborated on another issue in the original post which #193 addresses, so I should probably open up a new ticket to track that work instead.
