### ISSUE TITLE
This module needs a name_prefix for cluster and read replica names

### ISSUE THREAD

**Issue by gswallow** [terraform-google-modules/terraform-google-sql-db#196]
If I run terraform destroy and terraform apply without changing the name of the database cluster, Google will not allow the apply because you can't reuse a database name for a week for whatever reason.

Furthermore, if I try to inject my own randomness into the cluster name using random.id or uuid() I get an error from the module (GoogleCloudPlatform/sql-db/google//modules/postgresql version 4.4.0):

```
Error: Invalid for_each argument

  on .terraform/modules/sql_db/modules/postgresql/read_replica.tf line 24, in resource "google_sql_database_instance" "replicas":
  24:   for_each             = local.replicas

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

**Comment by morgante** [comment]
@gswallow Did you try setting the `random_instance_name` variable?

**Comment by gswallow** [comment]
Errr no. :)  

Thanks.
