### ISSUE TITLE
IAM users/service accounts

### ISSUE THREAD

**Issue by jtatum** [terraform-google-modules/terraform-google-sql-db#201]
Adding IAM users to cloud sql is a bit painful. Terraform has a `google_service_account` resource which gives easy access to the user's email. Unfortunately, IAM users need a stripped version of user email - per the docs:

> EMAIL: The email address of the service account. Due to length limit on database username, you need to omit the .gserviceaccount.com suffix in the email. For example, the username for the service account sa-name@project-id.iam.gserviceaccount.com should be sa-name@project-id.iam.

To get from `google_service_account.email` to `google_sql_user.name`, you need to do some fancy Terraform footwork with split, slice, join, etc. This seems like a good place for a module to help out - maybe if I give it an IAM service account, it handles that for me? Also it would be nice if the DB flags for IAM auth were enabled automatically if IAM users are supplied.

**Comment by morgante** [comment]
Good suggestion, we should add that logic here: https://github.com/terraform-google-modules/terraform-google-sql-db/blob/master/modules/postgresql/main.tf#L170

**Comment by g-awmalik** [comment]
I have this enhancement ready to go but blocked by [this](https://github.com/terraform-google-modules/terraform-google-sql-db/issues/211) kitchen int test issue. Seems like a gem version mismatch somewhere but haven't been able to pin point it.

**Comment by bharathkkb** [comment]
fixed via #218
