### ISSUE TITLE
CloudSQL Database becomes unmanageable from Terraform

### ISSUE THREAD

**Issue by sgravallon** [terraform-google-modules/terraform-google-sql-db#206]
Terraform version: 0.12

Terraform module used:
  source     = "GoogleCloudPlatform/sql-db/google//modules/mssql"
  version = "4.4.0"
Link: https://registry.terraform.io/modules/GoogleCloudPlatform/sql-db/google/4.0.0/submodules/mssql

There is one input parameter call "zone" that we specified in our terraform configuration tfvars file:

zone = "europe-west2-b"

We are also specifying the availability_type 

availability_type = "REGIONAL"

After a maintenance operation, the server restarted and on the console we can see the instance is located in europe-west2-c.

Problem: since the restart of the instance, our our pipeline is broken and terraform is failing with the following error:

 Error: Error, failed to update instance settings for : googleapi: Error 400: The incoming request contained invalid data., invalidRequest

We suspect that terraform is not able to retrieve the instance because the zone has changed - at creation we specified europe-west2-b but after the restart it is  located in europe-west2-c. 
We are not expecting such error because we specified the instance to be regional and believed that terraform would be able to reach the instance after a zone change, even if at initialization we specified a specific zone.

So currently our pipeline is broken and we are blocked.

(1) can you confirm our analysis
(2) What is the way to recover the situation ?

**Comment by villesau** [comment]
I'm experiencing similar problems. Zone should likely not be required setting for HA setup.
