### ISSUE TITLE
Terraform modules should output entire resource instead of individual attributes

### ISSUE THREAD

**Issue by andreykaipov** [terraform-google-modules/terraform-google-sql-db#207]
Adapted from #192:

Currently the modules output individual attributes of the resources they create. For example, in the [MySQL module](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/master/modules/mysql/outputs.tf#L28-L31):

```terraform
output "read_replica_instance_names" {
  value       = [for r in google_sql_database_instance.replicas : r.name]
  description = "The instance names for the read replica instances"
}
```

If we want to access any attributes that aren't outputs, for example finding the private IP addresses of the above replicas, we have to use a data source:

```terraform
data "google_sql_database_instance" "replicas" {
  for_each = toset(module.mysql.read_replica_instance_names)
  name     = each.value
  project  = var.project_id
}

output "private_ips" {
  value       = [for x in data.google_sql_database_instance.replicas : x.private_ip_address]
}
```

However, this doesn't make for good UX. If the module output the replicas directly, one wouldn't need to use a data source:

```terraform
// within terraform-google-sql-db/modules/mysql/outputs.tf
output "replicas" {
  value       = values(google_sql_database_instance.replicas)
  description = "A list of `google_sql_database_instance` resources representing the replicas"
}
```

Then a user could access any attributes they want without an intermediary data source:

```terraform
// within a parent module
output "private_ips" {
  value = [for x in module.mysql.replicas : x.private_ip_address]
}
```

**Comment by andreykaipov** [comment]
Relevant PR is https://github.com/terraform-google-modules/terraform-google-sql-db/pull/193

**Comment by des-esseintes** [comment]
this change is not compatible with terraform 0.15:

```
error	05-May-2021 15:29:32	Error: Output refers to sensitive values
error	05-May-2021 15:29:32	
error	05-May-2021 15:29:32	  on .terraform/modules/........./modules/postgresql/outputs.tf line 111:
error	05-May-2021 15:29:32	 111: output "instances" {
error	05-May-2021 15:29:32	
error	05-May-2021 15:29:32	Expressions used in outputs can only refer to sensitive values if the
error	05-May-2021 15:29:32	sensitive attribute is true.
```

**Comment by andreykaipov** [comment]
Hi @des-esseintes, have you tried Terraform v0.15.1? I don't have any issues using the latest release of this module.

There were [a few bug-fixes regarding sensitive values](https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md#0151-april-26-2021) in v0.15.1, and I believe one of these solves the issue you're seeing:

> - cli: Diagnostics messages will only indicate that a referenced value is sensitive if that value is directly sensitive, as opposed to being a complex-typed value that contains a sensitive value. (\#28442)
> - core: Loosen output value sensitivity requirement for non-root modules. This means that modules which may receive sensitive values as input variables no longer need to mark all related outputs as sensitive. The requirement for root modules to specify the sensitive attribute for sensitive values remains, with an extended diagnostic message to explain why. (\#28472)

Sure enough, when I try v0.15.0, I get the same error as you. I'd try v0.15.1.

If you're still having issues after upgrading, I'd recommend either opening up a new issue here so the team can better track it, or for Terraform core instead.

**Comment by des-esseintes** [comment]
thanks for the tip, @andreykaipov 
i've switched to newer tf version and it works as expected
