### ISSUE TITLE
can not update tier of postgresql when replica is enabled. 

### ISSUE THREAD

**Issue by st250467** [terraform-google-modules/terraform-google-sql-db#210]
Created postgresql with replica on GCP with same tier. but while updating the tier facing an issue-  "can not update instance master instance can not be larger than replica".

**Comment by st250467** [comment]
is there any way to update the replica first using terraform then master instance??

**Comment by kirecek** [comment]
I'm also wondering how to get this work within a single terraform apply. Obviously, a workaround is to use target in the apply and do it twice but it would very nice if the module could solve it on its own.

However, IMHO it's not that trivial to implement in terraform. Maybe some wait resource in the middle? But that's ugly.
