### ISSUE TITLE
Kitchen recipes failing => "Failed to complete #verify action: [cannot load such file -- google/apis/dns_v2beta1]"

### ISSUE THREAD

**Issue by g-awmalik** [terraform-google-modules/terraform-google-sql-db#211]
I'm able to create and converge successfully. However, upon verify I get this error for all 7 instances:

Exception
Class: Kitchen::ActionFailed
Message: 1 actions failed.
Failed to complete #verify action: [cannot load such file -- google/apis/dns_v2beta1] on mysql-public-local
----------------------
Please see .kitchen/logs/kitchen.log for more details
Also try running `kitchen diagnose --all` for configuration

**Comment by bharathkkb** [comment]
Hi @g-awmalik 
Looks like tests are broken on main. Could you try upgrading [inspec to latest](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/70205b0023df9ff68783fc1b7a5c4adf2dda90ef/test/integration/mssql-ha/inspec.yml#L17). [Example PR](https://github.com/terraform-google-modules/terraform-google-network/pull/216/files) where we did a similar upgrade, tests may need some rewrite.

**Comment by bharathkkb** [comment]
yup looks like bump should fix
https://github.com/inspec/inspec-gcp/issues/281

**Comment by g-awmalik** [comment]
Resolves with PR #216
