### ISSUE TITLE
Managing multiple google_service_networking_connection for same VPC, different cloudsql instances causes permadiff

### ISSUE THREAD

**Issue by yashbhutwala** [terraform-google-modules/terraform-google-sql-db#215]
### Terraform Version

0.14.7

### Affected Resource(s)

* google_service_networking_connection

### Terraform Configuration Files

```tf
resource "google_service_networking_connection" "private_vpc_connection" {
  provider = google-beta
  network  = data.google_compute_network.vpc.self_link
  service  = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.private_ip_address.name]
}
```

### Expected Behavior

* Two separate resources for two separate cloudsql instances should not cause permadiff during terraform apply.

### Actual Behavior

* Two separate resources for two separate cloudsql instances causes permadiff during terraform apply.

```
# module.cloudsql.google_service_networking_connection.private_vpc_connection will be updated in-place
  ~ resource "google_service_networking_connection" "private_vpc_connection" {
        id                      = "https%3A%2F%2Fwww.googleapis.com%2Fcompute%2Fv1%2Fprojects%2Fdev-1%2Fglobal%2Fnetworks%2Fdev:servicenetworking.googleapis.com"
      ~ reserved_peering_ranges = [
          - "private-ip-address-db-qa-db",
          + "private-ip-address-db-dev-db",
        ]
        # (3 unchanged attributes hidden)
    }
```

- https://github.com/terraform-google-modules/terraform-google-sql-db/blob/master/modules/private_service_access/main.tf#L41
- https://github.com/hashicorp/terraform-provider-google/issues/9092

**Comment by morgante** [comment]
It seems you're not using our module, so this should be addressed in the provider.

**Comment by morgante** [comment]
@yashbhutwala I see, it seems like you might be attempting to change the name when fed in?

I haven't encountered this issue before in the module.

**Comment by yashbhutwala** [comment]
@morgante I am not attempting to change the name, but to give more context, we have a "cloudsql module" that includes these resources `google_sql_database_instance.master`, `google_compute_global_address.private_ip_address` and `google_service_networking_connection.private_vpc_connection` and then using that module to make multiple cloudsql instances managed in a single statefile.  Since all the cloudsql instances live in a single VPC, I keep seeing a permadiff for the `google_service_networking_connection.private_vpc_connection` resource flapping between the different cloudsql instances.

**Comment by morgante** [comment]
I'd need to see your full configuration to understand the source of the issue, but it does plausibly seem like the problem might be with the source for the the `reserved_peering_ranges`.

**Comment by yashbhutwala** [comment]
It's essentially the same as what I sent in the original description, but here's more if it helps:


```

resource "google_compute_global_address" "private_ip_address" {
  provider = google-beta

  name          = "private-ip-address-db-${var.name}"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = var.gcp_network
  project       = var.gcp_project
}

resource "google_service_networking_connection" "private_vpc_connection" {
  provider = google-beta
  network  = data.google_compute_network.vpc.self_link
  service  = "servicenetworking.googleapis.com"
  reserved_peering_ranges = ["${google_compute_global_address.private_ip_address.name}"]
}

locals {
  db_instance_creation_delay_factor_seconds = 60
}

resource "null_resource" "cloudsql_network_delay" {
  depends_on = [google_service_networking_connection.private_vpc_connection]

  provisioner "local-exec" {
    command = "echo Gradual DB instance creation && sleep ${local.db_instance_creation_delay_factor_seconds}"
  }
}

resource "google_sql_database_instance" "master" {
  depends_on          = [google_service_networking_connection.private_vpc_connection, null_resource.cloudsql_network_delay]
  provider            = google-beta
  name                = "${var.name}-${random_string.instanceid.result}"
  database_version    = var.db_version
  region              = var.gcp_region
  project             = var.gcp_project
  deletion_protection = var.deletion_protection

  settings {
    location_preference {
      zone = var.gcp_zone
    }
    tier              = var.db_tier
    availability_type = var.db_availability
    maintenance_window {
      day  = var.maintenance_window_day
      hour = var.maintenance_window_hour
    }
    ip_configuration {
      ipv4_enabled = var.ipv4_enabled
      require_ssl  = var.require_ssl
      private_network = data.google_compute_network.vpc.self_link
    }
    
    dynamic "database_flags" {
      iterator = flag
      for_each = var.database_flags
      content {
        name = flag.key
        value = flag.value
      }
    }

    user_labels = var.tags
  }
}
```

**Comment by morgante** [comment]
Are you attempting to invoke this same code multiple times though? I only see a single instance listed.

I think there might be some confusion in how you're trying to do this. For a single VPC you should only have a *single* google_service_networking_connection resource.

**Comment by yashbhutwala** [comment]
Ahhh indeed, I think that's the confusion, so we shouldn't invoke `google_service_networking_connection` per cloudsql instance, i.e.: it probably doesn't belong in the module.  OK thanks @morgante

**Comment by morgante** [comment]
Yeah, that's why we put it in a separate module from the core instance module.

**Comment by morgante** [comment]
Yeah unfortunately it's not as clean as we might like. My usual approach is just to put the google_service_networking_connection creation as part of the network set up as it's not coupled to any particular instance.

**Comment by morgante** [comment]
Correct, that should be sufficient.
