### ISSUE TITLE
Hashicorp providers upgrade

### ISSUE THREAD

**Issue by fboula** [terraform-google-modules/terraform-google-sql-db#227]
Hi,

I am having a provider version issue with the current versions of `hashicorp/null` and `hashicorp/random` used by this module. Some other modules that we are using in our stack use a newer version of those providers, resulting in a conflict. 

```bash
>terraform init
...
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/random: no available releases match the given constraints ~> 2.2, ~>
3.1.0

>terraform providers                                      
.
├── provider[registry.terraform.io/hashicorp/vault]
└── module.test
    ├── provider[registry.terraform.io/hashicorp/google]
    ├── provider[registry.terraform.io/hashicorp/vault]
    ├── module.postgresql
    │   ├── provider[registry.terraform.io/hashicorp/google] ~> 3.53
    │   ├── provider[registry.terraform.io/hashicorp/null] ~> 2.1
    │   ├── provider[registry.terraform.io/hashicorp/random] ~> 2.2
    │   └── provider[registry.terraform.io/hashicorp/google-beta]
    ├── module.gcs
    │   ├── provider[registry.terraform.io/hashicorp/google] ~> 3.63.0
    │   └── provider[registry.terraform.io/hashicorp/random] ~> 3.1.0
```

Looking at the changelogs from both `null` and random it looks like the newer versions introduce any breaking changes to the `terraform-google-sql-db` module. 
- https://github.com/hashicorp/terraform-provider-null/blob/main/CHANGELOG.md
- https://github.com/hashicorp/terraform-provider-random/blob/main/CHANGELOG.md

Could it be possible to update those providers ? I would be glad to create PR to do if you allow it.   

Thanks

**Comment by morgante** [comment]
Sure, feel free to open a PR upgrading to 3.x versions.

**Comment by fboula** [comment]
Fixed via Pull request, waiting for release :crossed_fingers:
