### ISSUE TITLE
PostgreSQL module: Sensitive value errors creating new instance

### ISSUE THREAD

**Issue by samcre** [terraform-google-modules/terraform-google-sql-db#229]
I'm trying to create a new **private** PostgreSQL Cloud SQL instance using `terragrunt v0.31.0` and `terraform v1.0.0`.

Using the latest version of the PostgreSQL module (`v5.1.1`), when I run `terragrunt plan` or `terragrunt apply`, It throws these errors:

```
╷
│ Error: Output refers to sensitive values
│ 
│   on outputs.tf line 101:
│  101: output "primary" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true
╵
╷
│ Error: Output refers to sensitive values
│ 
│   on outputs.tf line 111:
│  111: output "instances" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true
```

Here is the `terragrunt-debug.tfvars.json`, which contains the variable's values for the module:
```
{
  "availability_type": "ZONAL",
  "database_version": "POSTGRES_11_10",
  "enable_default_db": false,
  "ip_configuration": {
    "authorized_networks": [],
    "ipv4_enabled": false,
    "private_network": "https://www.googleapis.com/compute/v1/projects/mocked/global/networks/mocked",
    "require_ssl": null
  },
  "name": "mocked",
  "project_id": "mocked",
  "region": "europe-west1",
  "tier": "db-f1-micro",
  "zone": "europe-west1b"
}
```

Should be resolved setting `primary` and `instances` outputs as `sensitive`?

**Comment by morgante** [comment]
This is a bit of a complicated nuance and frankly I think terragrunt needs to do a better job here.

In Terraform core, only outputs from the *root module* need to be marked as sensitive. Terraform [fixed this](https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md#0151-april-26-2021) in v0.15.1.

This module should never be used directly as a root module. The way Terraform works is that you should have your own root module which calls other modules. Terragrunt encouraging you to directly use this module as a root module is an anti-pattern.

Note: we will accept a PR to mark these values as sensitive, but they really shouldn't be. Terragrunt needs to do better here.

**Comment by samcre** [comment]
Thanks for the feedback. I will create an internal module to call this one, and prevent the sensitive output to be viewed.
