### ISSUE TITLE
tfsec fail with "Potentially sensitive data stored in "default" value of variable."

### ISSUE THREAD

**Issue by tuxmonteiro** [terraform-google-modules/terraform-google-sql-db#233]
When using tfsec to improve security check, it's fail with GEN001 code: "Potentially sensitive data stored in "default" value of variable."

https://tfsec.dev/docs/general/GEN001/

The recommendation is "Don’t include sensitive data in variable defaults".

Is It possible changes the code to validate sensitive variable is null instead if it contains a "empty string" in this case?

**Comment by morgante** [comment]
tfsec is a third party product, not part of native Terraform. We focus on working well with native Terraform, not arbitrary tools.

An empty string is clearly not sensitive information. I suggest filing a bug with tfsec to have them improve their detectors.

**Comment by tuxmonteiro** [comment]
tflint is a security lint and I only mentioned it because I agree that the approach is not recommended, because there is the potential risk of this approach suggesting a default password, if in the future the code changes the current behavior of making it random if empty.

As a sensitive input variable, the suggestion by hashicorp itself is that passwords are always protected. Why not testing if it null instead empty (by default)?

**Comment by morgante** [comment]
> tflint is a security lint and I only mentioned it because I agree that the approach is not recommended, because there is the potential risk of this approach suggesting a default password

Accepting sensitive values as inputs is a standard Terraform convention.

> As a sensitive input variable, the suggestion by hashicorp itself is that passwords are always protected. Why not testing if it null instead empty (by default)?

Passwords *are* always protected. The blank value is never used as the password.

----
`null` and `""` are functionally equivalent. Again, it is a bug in tfsec to treat them differently. Working around bugs in other products is nor our priority.
