### ISSUE TITLE
Terraform refusing to run due to sensitive outputs.

### ISSUE THREAD

**Issue by GrantSheehan** [terraform-google-modules/terraform-google-sql-db#238]
Hey Google team, it looks like at least as of Terraform v1.0.4, some of these module's outputs are considered sensitive and the module refuses to apply as-is:

```
╷
│ Error: Output refers to sensitive values
│ 
│   on outputs.tf line 101:
│  101: output "primary" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true
╵
╷
│ Error: Output refers to sensitive values
│ 
│   on outputs.tf line 111:
│  111: output "instances" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true
╵
ERRO[0004] 1 error occurred:
	* exit status 1
```
I can PR a fix with `sensitive = true` added to that output, if that's the approach you'd like to take to resolve the issue.

**Comment by morgante** [comment]
How are you trying to use the module?

This restriction only applies to *root* modules (where you run `terraform apply` from). You should not be running `terraform apply` directly from the repo, but instead reference the module from your own configuration (as shown in the README).

**Comment by morgante** [comment]
This is a bug in Terragrunt then. Please file an issue with them, as their behavior is inconsistent with Terraform core.

More context: https://github.com/terraform-google-modules/terraform-google-sql-db/issues/229#issuecomment-866945524
