### ISSUE TITLE
Module not usable with Terraform >= 0.15 (MySQL)

### ISSUE THREAD

**Issue by JulienJourdain** [terraform-google-modules/terraform-google-sql-db#244]
Hello,

I tried to upgrade module in my code from `4.5.0` to `6.0.0` and I was surprised to see the following error when I applied:
```bash
❯ terraform apply -var-file $(terraform workspace show).tfvars

╷
│ Error: Output refers to sensitive values
│ 
│   on .terraform/modules/mysql/modules/mysql/outputs.tf line 106:
│  106: output "primary" {
│ 
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
╵
╷
│ Error: Output refers to sensitive values
│ 
│   on .terraform/modules/mysql/modules/mysql/outputs.tf line 116:
│  116: output "instances" {
│ 
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
```

It seems like due to attributes declared as **`sensitive`** in [`sql_database_instance`](https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_sql_database_instance.go#L467) resource _(used in this module)_, this module is not working correctly with Terraform >= 0.15 because of missing `sensitive` setting on `primary` and `instances` outputs that you find [here](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/306474400b4e83f0c335f045642e3029f599bec9/modules/mysql/outputs.tf#L106).

IMO, the fix consists at least on adding `sensitive = true` to the `primary` and `instances` outputs in `terraform-google-modules/terraform-google-sql-db/blob/master/modules/mysql/outputs.tf`.

I can prepare a small pull request to do this if you're ok with this :-)

**Comment by bharathkkb** [comment]
Hi @JulienJourdain 
TF fixed this [bug](https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md#0151-april-26-2021) in 0.15.1. Now only your root modules where you invoke the module need to make this as sensitive. Feel free to reopen if the issue persists.
