### ISSUE TITLE
Add the possibility to create an instance as a clone of another instance

### ISSUE THREAD

**Issue by gcamus59** [terraform-google-modules/terraform-google-sql-db#253]
Hi,

We would like to leverage the [clone feature](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#clone) from the google_sql_database_instance terraform resource. That would allow module's users to create a new Cloud SQL Instance as a clone from another instance.

Can I craft a Pull Request to add this feature into the terraform-google-sql-db Terraform module?

Thanks

**Comment by morgante** [comment]
I'm not sure if we want to support this in the module. The clone functionality is not especially declarative and has been error-prone in the past.

If you already have the other instance settings in Terraform, can you simply create a new instance with the same settings?
