### ISSUE TITLE
compute disk in terraform --An argument named "replica_zones" is not expected here

### ISSUE THREAD

**Issue by balagaa** [terraform-google-modules/terraform-google-sql-db#260]
An argument named "replica_zones" is not expected here
*****************************************************
1. provider.tf 
*****************************************************
provider "google" {
  project = "xxxxx"
}

terraform {
  required_providers {
    google = {
      version = "~> 3.68.0"
    }
  }
}
************************************************
2. Compute disk : 
*****************************************************
resource "google_compute_disk" "tfer-dsk-ssd-wal-prod-01" {
  name                      = "xxxxxx"
  project                   = "xxxxx"
  size                      = "500"
  type                      = "pd-standard"
  physical_block_size_bytes = 4096

  replica_zones = ["europe-west1-b", "europe-west1-d"]
}

**Comment by bharathkkb** [comment]
Hi @balagaa 

This does not seem related to this module as you are directly using `google_compute_disk` resource. You might also be using the wrong resource, please review if you wanted to use https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_disk.  For further questions related to the resources open a bug/question in the [provider](https://github.com/hashicorp/terraform-provider-google) repo.
