### ISSUE TITLE
Override default read-replica names.

### ISSUE THREAD

**Issue by mans0954** [terraform-google-modules/terraform-google-sql-db#266]
### TL;DR

Make it possible to override the default name that this module generates for read replicas on a per-replica basis. This would be useful when importing existing resources into Terraform, or other considerations require a custom naming scheme.

### Detailed design

E.g. something like:

In `variables.tf`:
```
// Read Replicas
variable "read_replicas" {
  description = "List of read replicas to create. Encryption key is required for replica in different region. For replica in same region as master set encryption_key_name = null"
  type = list(object({
    name            = string
    name_override   = optional(string)
...
```
In `read_replica.tf`:
```
resource "google_sql_database_instance" "replicas" {
  provider             = google-beta
  for_each             = local.replicas
  project              = var.project_id
  name                 = each.value.name_override == null ? "${local.master_instance_name}-replica${var.read_replica_name_suffix}${each.value.name}" : each.value.name_override
```
Unfortunately this approach requires opting into the `module_variable_optional_attrs` experiment, but perhaps there are other approaches?

**Comment by bharathkkb** [comment]
Sorry for the delay @mans0954
I think we can add an override attrib. Regarding optional agreed, it would be cleaner if we had that and this would not be a breaking change which is coming in 1.3 https://github.com/hashicorp/terraform/releases/tag/v1.3.0-beta1
