### ISSUE TITLE
Import for DB/Replica

### ISSUE THREAD

**Issue by romankor** [terraform-google-modules/terraform-google-sql-db#270]
### TL;DR

Is importing supported by the module ? I dont seem to find any documentation on that. 
If thats not supported , I would like to put in a feature request for it

**Comment by bharathkkb** [comment]
Hi @romankor 
Here is an example for importing a db into the statefile: https://github.com/terraform-google-modules/terraform-google-sql-db/issues/257#issuecomment-989172659
Feel free to reopen if still an issue.
