### ISSUE TITLE
safer_mysql module variable assign_public_ip configures ipv4_enabled variable in mysql module

### ISSUE THREAD

**Issue by mkyc** [terraform-google-modules/terraform-google-sql-db#287]
### TL;DR

In `modules/safer_mysql/main.tf` there is this section: 

```
ip_configuration = {
    ipv4_enabled = var.assign_public_ip
}
```

.... and this looks pretty weird TBH

### Expected behavior

IMO variables should be named the same and mentioned part should be:

```
ip_configuration = {
    ipv4_enabled = var.ipv4_enabled
}
```

### Terraform Configuration

```hcl
n/a
```

### Terraform Version

```sh
n/a
```

### Additional information

version 10.0.0

**Comment by bharathkkb** [comment]
Thanks for the report @mkyc My understanding is that it was set to `assign_public_ip` to make it clearer to the user of the safer cluster that this option will assign a public ip (and possibly less secure). 
Do the descriptions help make it clearer?  
https://github.com/terraform-google-modules/terraform-google-sql-db/blob/c51bf296e392fca246aae1c9ba4299a5a97ef274/modules/safer_mysql/variables.tf#L160-L164
