### ISSUE TITLE
 Error 400: Missing parameter: Root Password., required

### ISSUE THREAD

**Issue by ShibraAmin18** [terraform-google-modules/terraform-google-sql-db#312]
![image](https://user-images.githubusercontent.com/87754284/172414800-d6651a51-40c7-4c58-bd05-e1ebd923fe22.png)

Can't find any variable for the root password in the PostgreSQL module.

Or is it related to some authentication issue with gcloud ?

**Comment by bharathkkb** [comment]
Hi @ShibraAmin18 
Can you paste your reproducible Terraform configuration without any sensitive values?

**Comment by ShibraAmin18** [comment]
Hey @bharathkkb 
I figured this was `database_version` value error. I used `database_version  = "14"` instead of `database_version  = "POSTGRES_14"` .

But don't know why it gives such an error `Missing parameter: Root Password., required `.
If it would have been a valid version error, I could have been updated earlier only.

Thanks.
