### ISSUE TITLE
Properties are not documented well

### ISSUE THREAD

**Issue by j-windsor** [terraform-google-modules/terraform-google-sql-db#349]
Several properties on this module are not documented well. Here are some examples in the Postgres module:

- `additional_databases`: no idea what valid values are for charset and collation.
- `backup_configuration` and `additional_users`: no documentation but luckily the properties are well named so I can figure it out.
- `ip_configuration`: Literally no idea where to start with this object. What goes in `authorized_networks`? All I know about it is the type `list(map(string))` which could be anything. I would guess `private_network` is a self link to something, but is it a google_compute_network resource or something else?
- `read_replicas`: Really no idea where to start here either.

Please improve documentation so users don't have to fish through the implementation to determine how to set properties.

**Comment by bharathkkb** [comment]
@j-windsor some like additional_databases , backup_config, additional_users, read_replicas are currently defined in the docs [1]. We should improve authorized_networks.

[1]: https://github.com/terraform-google-modules/terraform-google-sql-db/tree/master/modules/postgresql#inputs

**Comment by philip-harvey** [comment]
Why is additional_users a list and not a map?  Making it a list seems to make it more complex than it needs to be.
