### ISSUE TITLE
Bumping version of null plugin is creating hard to trace version conflicts

### ISSUE THREAD

**Issue by mmllc-jsilverman** [terraform-google-modules/terraform-google-sql-db#371]
https://github.com/terraform-google-modules/terraform-google-sql-db/blob/b7e9789307470fe0ae10d9b3ba901ee51eef6e53/modules/postgresql/versions.tf#L22

Perhaps this is not the right place for this, but I've traced a version conflict to this module.

```
│ Could not retrieve the list of available versions for provider hashicorp/null: no available releases match the given constraints ~> 3.1.0, ~> 3.2
```

Why does the null plugin need to have its version declared in this module, anyway?

**Comment by apeabody** [comment]
Hi @mmllc-jsilverman - Thanks for the feedback, we've adjusted the null provider version constraint to be inclusive of both the original 3.1.x, and additional 3.x releases.
