### ISSUE TITLE
alloated_ip_range should be optional

### ISSUE THREAD

**Issue by enocom** [terraform-google-modules/terraform-google-sql-db#389]
### TL;DR

allocated_ip_range is required here, but optional in the provider (and the Cloud SQL Admin API)

### Expected behavior

The field should be optional.

### Observed behavior

The field is required. See https://github.com/terraform-google-modules/terraform-google-sql-db/blob/71b04fc59bce61bf108d012a83fe0ecf3b0922e9/modules/safer_mysql/variables.tf#L52.

### Terraform Configuration

```hcl
n/a
```

### Terraform Version

```sh
n/a
```

**Comment by ibhaskar2** [comment]
This issue has been fixed in https://github.com/terraform-google-modules/terraform-google-sql-db/pull/395

**Comment by enocom** [comment]
Tahnks @ibhaskar2!

**Comment by g-awmalik** [comment]
Thanks a lot taking care of this @ibhaskar2. I'm going to close this for now.

**Comment by enocom** [comment]
@g-awmalik has this been released as part of a recent tag?

**Comment by g-awmalik** [comment]
@enocom - this should be available with v14.0.0. We should be releasing that early next week.

**Comment by enocom** [comment]
Thank you!
