### ISSUE TITLE
Support For Deny Maintenance Period

### ISSUE THREAD

**Issue by rubencepeda** [terraform-google-modules/terraform-google-sql-db#391]
### TL;DR

In the latest version of the GCP Terraform provider there is support for setting the Deny Maintenance Period.  This is an important feature specially for ecommerce applications. 

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance See: settings.deny_maintenance_period
```

**Comment by g-awmalik** [comment]
Closing this issue since the PR has been merged and should be available with v14.0
