### ISSUE TITLE
While changing the root_password for MSSQL server is destroying the instance and then creating the new instance 

### ISSUE THREAD

**Issue by sk251319** [terraform-google-modules/terraform-google-sql-db#405]
### Expected behavior

Terraform should do not destroy the instance if we are changing the root-password.

### Observed behavior
When I am changing the root_password for the existing MSSQL instance rather that doing the in-place edit it is destroying the instance and then recreating the instance. 

we can change root_password using GCP console and gcloud utility and it is not recreating the instance but using terraform it is recreating the instance. 

_No response_

### Terraform Configuration

```hcl
Provider version 
google      = "~> 3.61.0"
google-beta = "~> 3.61.0"
```

### Terraform Version

```sh
Provider version
google      = "~> 3.61.0"
google-beta = "~> 3.61.0"
```

**Comment by sk251319** [comment]
Can anyone confirm someone is looking into that as it is a showstopper for me.

**Comment by DeLoWaN** [comment]
I've just tested it: I changed the root_password, it did not do anything: no change in the database instance. Fortunately, that was a test instance, I destroyed and recreated it.
