### ISSUE TITLE
Unable to boot the RDS postgress SQL inside the VPC

### ISSUE THREAD

**Issue by tejesh2311** [terraform-google-modules/terraform-google-sql-db#41]
hi,
I am trying to boot my RDS PostgreSQL inside a VPC using a terraform code. I had followed the above two and also the other examples in the the repo but couldn't had any luck.

```    
ip_configuration {
        ipv4_enabled = true
        private_network = "10.10.22.0/24"
        }
```
earlier to this i had tried
```   
 ip_configuration {
        ipv4_enabled = true
        authorized_networks = [{
          name  = "${var.network_name}"
          value = "10.10.22.0/24"
```

Can you help me here or guide me how i can bring this into the VPC?

**Comment by namusyaka** [comment]
Could you provide a minimal repo for reproducing ur issue?

**Comment by aaron-lane** [comment]
@tejesh2311 please reopen this issue if you can provide more information.
