### ISSUE TITLE
Password validation feature forces all passwords to be replaced

### ISSUE THREAD

**Issue by kpocius** [terraform-google-modules/terraform-google-sql-db#418]
### TL;DR

https://github.com/terraform-google-modules/terraform-google-sql-db/pull/376 introduced password validation feature and set `special = true` on `random_password` resource, which forces it to be re-created and thus change the password for all users.

### Expected behavior

I'd expect passwords to remain untouched if the new feature isn't used.

### Observed behavior

Random password is regenrated and user updated:
```
  # module.argo-workflows-dev-db-postgresql.google_sql_user.default[0] will be updated in-place
! resource "google_sql_user" "default" {
        id                      = "argo//argo-workflows-dev-db"
        name                    = "argo"
!       password                = (sensitive value)
        # (5 unchanged attributes hidden)
    }

  # module.argo-workflows-dev-db-postgresql.random_password.user-password must be replaced
-/+ resource "random_password" "user-password" {
!       bcrypt_hash = (sensitive value)
!       id          = "none" -> (known after apply)
!       result      = (sensitive value)
!       special     = false -> true # forces replacement
        # (10 unchanged attributes hidden)
    }
```

### Terraform Configuration

```hcl
N/A
```

### Terraform Version

```sh
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.51.0
+ provider registry.terraform.io/hashicorp/google-beta v4.51.0
+ provider registry.terraform.io/hashicorp/http v3.2.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/winebarrel/mysql v1.10.6
```

**Comment by kpocius** [comment]
An obvious workaround would be to set the password manually, but we have 50+ databases, so if it's possible to avoid doing that, it would be amazing.

**Comment by KrustyHack** [comment]
Ay,

We got the same problem here, even if we're not using random password feature. We manually set all password from a secret :

```
    {
      name            = "xxx"
      password        = data.doppler_secrets.xxx.map.PASSWORD
      random_password = false
    },
```

But it still trigger the same problem as @kpocius :

```
  # module.xxx.module.postgresql.random_password.user-password must be replaced
-/+ resource "random_password" "user-password" {
      ~ bcrypt_hash = (sensitive value)
      ~ id          = "none" -> (known after apply)
      ~ result      = (sensitive value)
      ~ special     = false -> true # forces replacement
        # (10 unchanged attributes hidden)
    }
```

I don't understand what's happening here. :grimacing:

**Comment by kpocius** [comment]
@KrustyHack, `random_password` resource is not conditional, so it is applied even if you don't end up using it. I believe in your case it is safe to apply -- it will regenerate those passwords, but they won't be used anywhere.

**Comment by philip-harvey** [comment]
The fix from @bharathkkb will also resolve this issue once it's merged

**Comment by bharathkkb** [comment]
Sorry for the delay everyone! https://github.com/terraform-google-modules/terraform-google-sql-db/pull/421 is merged
