### ISSUE TITLE
Add outputs for 'user_name' & 'db_name'

### ISSUE THREAD

**Issue by anismoula123** [terraform-google-modules/terraform-google-sql-db#472]
### TL;DR

to use the default username & db name from another terraform layer we need to expose them as output

### Terraform Resources

```markdown
resource "google_sql_database" "default"
resource "google_sql_user" "default"
```

**Comment by imrannayer** [comment]
@anismoula123 both values are passed as an input to the module. Can you plz grab them directly from the variables you are passing?
