### ISSUE TITLE
Issue With SSL Mode on v18.0.0. change provider min version to 5.6 for postgres module.

### ISSUE THREAD

**Issue by GusPrice** [terraform-google-modules/terraform-google-sql-db#552]
### TL;DR

Get the following error from Terraform when using the postgres module

```
Error: Unsupported argument
on .terraform/modules/postgres_db/modules/postgresql/main.tf line 108, in resource "google_sql_database_instance" "default":
        ssl_mode                                      = lookup(ip_configuration.value, "ssl_mode", null)
An argument named "ssl_mode" is not expected here.
```

### Expected behavior

Expect ssl_mode to be applied appropriately.

### Observed behavior

See error above.

### Terraform Configuration

```hcl
On module v18.0.0


  ip_configuration = {
    ipv4_enabled    = false
    private_network = data.google_compute_network.primary_network.id
    require_ssl     = true
    ssl_mode        = "TRUSTED_CLIENT_CERTIFICATE_REQUIRED"
  }
```
I also tried
```
  ip_configuration = {
    ipv4_enabled    = false
    private_network = data.google_compute_network.primary_network.id
    require_ssl     = false
    ssl_mode        = "TRUSTED_CLIENT_CERTIFICATE_REQUIRED"
  }
```

The rest of my configuration works without ssl_mode on v17.1.0
```


### Terraform Version

```sh
Terraform Version 1.6.5

    google = {
      version = "~> 4.84.0"
    }

    google-beta = {
      version = "~> 4.84.0"
    }
```

**Comment by volver-13** [comment]
Seems like the module should require a minimum of v5.6.0 provider version

https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.6.0

_sql: added ssl_mode field to google_sql_database_instance resource (https://github.com/hashicorp/terraform-provider-google/pull/16394)_

**Comment by ykyr** [comment]
There was just [v19.0 released](https://github.com/terraform-google-modules/terraform-google-sql-db/releases), without change for the minimum google provider version :(
