### ISSUE TITLE
Should the additional_users output match the order of the additional_users input?

### ISSUE THREAD

**Issue by kdeggelman** [terraform-google-modules/terraform-google-sql-db#555]
### TL;DR

My input looks like this
```tf
  additional_users = [
    {
      name            = "admin"
      password        = null
      random_password = true
    },
    {
      name            = "sales"
      password        = null
      random_password = true
    },
    {
      name            = "marketing"
      password        = null
      random_password = true
    }
  ]
}
```

The output looks like this:
```json
[
  { "name": "admin", "password": "<redacted>" },
  { "name": "marketing", "password": "<redacted>" },
  { "name": "sales", "password": "<redacted>" }
]
```

I would expect the ordering here to match up. That way in other terraform resources I can use the index of the outputs as values to other inputs. For example, if I want to create a `google_bigquery_connection` for the sales user I could use
```tf
    credential {
      username = module.sql-db.additional_users[1].name
      password = module.sql-db.additional_users[1].password
    }
```
but `additional_users[1]` ends up as the marketing user.

### Terraform Resources

```markdown
As noted above, I'm also using https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_connection
```

**Comment by kdeggelman** [comment]
My guess is that this functionality is dictated by this line, which to my (limited) understanding of Terraform creates a map from the ordered list of `additional_users`.
https://github.com/terraform-google-modules/terraform-google-sql-db/blob/ca9cf76ec2fa57f8410b09ea88cdfb5f3a2b1ab6/modules/postgresql/main.tf#L28
Given that the map is keyed by `name`, is it safe to say that the ordering will be alphabetical by name?

**Comment by imrannayer** [comment]
@kdeggelman thats the nature of maps. You can retrieve them using keys.

**Comment by kdeggelman** [comment]
I may have made my original question too confusing. Here's my current understanding:
  * The `additional_users` input is an array
  * The `additional_users` output is an array
  * The output array is sorted by alphabetical order of the  `name` attribute.
  * Unless the input array happens to be sorted this way as well, the ordering of the input and output will be different.

Is that all correct?
