### ISSUE TITLE
Unable to set maintenance windows for replicas

### ISSUE THREAD

**Issue by arielsalvo** [terraform-google-modules/terraform-google-sql-db#64]
According to Google's [docs](https://cloud.google.com/sql/docs/mysql/instance-settings), in the *Maintenance Windows* section, 2nd gen instances do not allow setting any explicitly:

> Read replicas do not support the maintenance window setting; they can experience a disruptive upgrade at any time. Failover replicas have the same maintenance window as the primary instance, and are updated immediately before the primary.

I seem to be unable to setup replicas without specifying a maintenance window and applying the default config will result in error.

```
  ~ module.cloud_sql_prd.google_sql_database_instance.failover-replica
      settings.0.maintenance_window.#:                               "0" => "1"
      settings.0.maintenance_window.0.day:                           "" => "6"
      settings.0.maintenance_window.0.hour:                          "" => "3"
      settings.0.maintenance_window.0.update_track:                  "" => "stable"

  ~ module.cloud_sql_prd.google_sql_database_instance.replicas
      settings.0.maintenance_window.#:                               "0" => "1"
      settings.0.maintenance_window.0.day:                           "" => "1"
      settings.0.maintenance_window.0.hour:                          "" => "3"
      settings.0.maintenance_window.0.update_track:                  "" => "canary"
```
Is the error in my code and there's a way to bypass this config or should this be considered in the module?

Thanks!
    --Ariel

**Comment by mr-andyd** [comment]
I am also experiencing this issue. I have no maintenance window block within my module that contains the read replica resource, however, when I try and apply Terraform, it tries to create one. I have even tried to create a read replica manually and then perform a terraform import, however, it still tries to add the maintenance window block. I am also seeing this with the availability type, for some reason, it does not want to be set to ZONAL.
