### ISSUE TITLE
Google Terraform provider support version 6.x.x+

### ISSUE THREAD

**Issue by k4leung4** [terraform-google-modules/terraform-google-sql-db#641]
### TL;DR

The Google Terraform Provider released version 6.0.0 on August 26; https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.0.0.
It would be nice if this module supported version 6.x.x.

**Comment by lra** [comment]
Will be fixed by https://github.com/terraform-google-modules/terraform-google-sql-db/pull/635
