### ISSUE TITLE
Latest version on hashicorp registry is out of date

### ISSUE THREAD

**Issue by katherine-circularise** [terraform-google-modules/terraform-google-sql-db#650]
### TL;DR

Latest version on the registry is still 21.0.0 as opposed to being 22.0.0.
See: https://registry.terraform.io/modules/terraform-google-modules/sql-db/google/latest

### Terraform Configuration

```hcl
n/a
```

### Terraform Version

```sh
n/a
```

**Comment by imrannayer** [comment]
fixed
