### ISSUE TITLE
SQL Server Module

### ISSUE THREAD

**Issue by graziergeek** [terraform-google-modules/terraform-google-sql-db#66]
Are there plans or a timeline for a cloud sql module for sql server?
Thanks

**Comment by morgante** [comment]
Not currently planned, but we can definitely work on it.

Documentation/reference: https://cloud.google.com/sql/docs/sqlserver/create-instance#create-instance-sqlserver-curl

**Comment by kopachevsky** [comment]
we do have bug in provider stopping us from implementing this issue https://github.com/terraform-providers/terraform-provider-google/issues/4776

**Comment by namusyaka** [comment]
Closed via #68 and #112
