### ISSUE TITLE
Cannot provision Postgres database

### ISSUE THREAD

**Issue by jbunce** [terraform-google-modules/terraform-google-sql-db#67]
New project in GCP with zero provisioned databases. Timeout after 20 minutes with:

```
Error: Error, failed to create instance dev-1608296: googleapi: Error 409: The instance or operation is not in an appropriate state to handle the request., invalidState

  on ../../modules/postgres/main.tf line 10, in resource "google_sql_database_instance" "default":
  10: resource "google_sql_database_instance" "default" {
```

```
resource "google_sql_database_instance" "default" {
  project          = "${var.project_id}"
  name             = "${var.db_instance_name}"
  database_version = "${var.db_version}"
  region           = "${var.region}"

  settings {
    tier = "${var.db_instance_tier}"
  }
}

resource "google_sql_database" "default" {
  name       = "${var.db_name}"
  project    = "${var.project_id}"
  instance   = "${google_sql_database_instance.default.name}"
  depends_on = ["google_sql_database_instance.default"]
}
```

**Comment by jbunce** [comment]
I tried deleting the `terraform.tfstate` and `terraform.tfstate.backup` and re-running the `terraform apply` and received the same error.

**Comment by jbunce** [comment]
It looks like I'm hitting https://github.com/hashicorp/terraform/issues/20972 which was closed by automation. I changed the name of the database instance and I now have a provisioned database.

**Comment by morgante** [comment]
Looks like this is a Terraform provider issue. If you encounter it again, please open an issue on the provider: https://github.com/terraform-providers/terraform-provider-google/issues
