### ISSUE TITLE
Enabling high availability for mysql instances

### ISSUE THREAD

**Issue by alejandro-delgado-garcia** [terraform-google-modules/terraform-google-sql-db#71]
Is there any support in this module to enable high availability for MySQL instances?

**Comment by morgante** [comment]
Yes, you can configure the failover replica and associated settings. See the available inputs here: https://github.com/terraform-google-modules/terraform-google-sql-db/tree/master/modules/mysql#inputs

**Comment by alejandro-delgado-garcia** [comment]
Hi @morgante it seems that cloud SQL 2nd generation instances doesn't use a replica for the failover according to google docs https://cloud.google.com/sql/docs/mysql/high-availability#legacy_mysql_high_availability_option

**Comment by alejandro-delgado-garcia** [comment]
In the Terraform docs, there is a property not supported by this module https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#availability_type which might work to enable this, although in the docs they just mentioned Postgres but I think it could also work for MySQL

**Comment by morgante** [comment]
I see, yes it looks like we would have to do some work to support the new version of high availability.

**Comment by axot** [comment]
Hi, due to the official document(https://cloud.google.com/sql/docs/mysql/configure-ha), I think it should work to setup with `availabilityType":"REGIONAL"` and `backupConfiguration` in current version.

```
curl --header "Authorization: Bearer ${ACCESS_TOKEN}" \
     --header 'Content-Type: application/json' \
     --data '{"name":"[INSTANCE_NAME]", "region":"[REGION]",
              "databaseVersion":"[DATABASE_VERSION]",
              "settings": {
                  "tier":"[MACHINE_TYPE]",
                  "backupConfiguration": {"binaryLogEnabled": true, "enabled": true},
                  "availabilityType":"REGIONAL"}}' \
     -X POST \
     https://www.googleapis.com/sql/v1beta4/projects/[PROJECT-ID]/instances
```

**Comment by alejandro-delgado-garcia** [comment]
Hi everyone, is there any progress about this issue? Thanks!

**Comment by morgante** [comment]
@alejandro-delgado-garcia Not currently, though I'd be happy to review a PR if anyone wants to take a stab at it.

**Comment by mehdicopter** [comment]
It works the same way as postgres.
Just add `availability_type = var.availability_type` into `settings` and add this block into variables.tf and it will work like a charm on MySQL instances.

```
variable "availability_type" {
  description = "The availability type for the master instance. Can be either ZONAL or REGIONAL."
  type        = string
  default     = "ZONAL"
}
```

**Comment by v-morlock** [comment]
@mehdicopter in my case, this gives `Error: Error, failed to update instance settings for : googleapi: Error 400: The incoming request contained invalid data., invalidRequest`

**Comment by alejandro-delgado-garcia** [comment]
> @mehdicopter in my case, this gives `Error: Error, failed to update instance settings for : googleapi: Error 400: The incoming request contained invalid data., invalidRequest`

Could you please share what's the value you used to set the `availability_type`? Valid values should be `ZONAL` or `REGIONAL`
Please also be aware that this setting is still not available in this repo.

**Comment by mehdicopter** [comment]
Which version of google provider do you have?

**Comment by iniinikoski** [comment]
Hi,

We are experiencing the same issue here as @alejandro-delgado-garcia, same error.

Here's the snippet:

```
resource "google_sql_database_instance" "instance" {
  provider = google-beta
  project  = local.service_project_id

  # name   = "private-instance-${random_id.db_name_suffix.hex}"
  name = local.instance_name
  # region = "us-central1"
  region = "europe-west1"

  depends_on = [google_service_networking_connection.private_service_access]

  settings {
    tier              = "db-n1-standard-1"
    availability_type = "REGIONAL"
    ip_configuration {
      ipv4_enabled = false
      # private_network = google_compute_network.private_network.self_link
      private_network = data.google_compute_network.main.self_link
    }
  }
}
```

**Comment by iniinikoski** [comment]
And, if I do

```
availability_type = "ZONAL"
```

no error.

 Googol Terraform provider version is the latest and greatest now, 3.14.0.

Terraform core version is 0.12.20.

**Comment by iniinikoski** [comment]
Hi,

See this one: https://github.com/terraform-providers/terraform-provider-google/issues/5286

So, apparently the API and gcloud does not support the REGIONAL, hence the problem... Not good...

**Comment by Dev25** [comment]
@iniinikoski Tried enabling binary logs?
https://github.com/terraform-providers/terraform-provider-google/issues/5022

here's the non module way of doing it:
```tf
resource "google_sql_database_instance" "test" {
  name             = "test"
  region           = "europe-west1"
  database_version = "MYSQL_5_7"

  settings {
    tier              = "db-n1-standard-1"
    availability_type = "REGIONAL"

    backup_configuration {
      binary_log_enabled = true
      enabled            = true
    }

    ip_configuration {
      ipv4_enabled = true
    }
  }
}
```

This module still requires a update to the `mysql/main.tf ` to include `availability_type`

**Comment by iniinikoski** [comment]
@Dev25 ouch, of course I forgot that part... :) Looks perfection now. Looks like weekend awaits ;) Thanks!

**Comment by rebelthor** [comment]
@morgante : Seems like @Dev25 and @cromaniuc added some PRs to this issue. Is the offer to review them still available? Thanks!

**Comment by alejandro-delgado-garcia** [comment]
Thank you everyone. This is really good
