### ISSUE TITLE
output empty

### ISSUE THREAD

**Issue by sagivle** [terraform-google-modules/terraform-google-sql-db#8]
not getting any outputs from module

  module "mysql-db" {
    source           = "GoogleCloudPlatform/sql-db/google"
    version          = "1.0.0"
    name             = "${var.deploy_name}"
    database_version = "MYSQL_5_7"
    disk_autoresize = true
    region = "${var.region}"
    location_preference = "${var.location_preference}"
  }

output "instance_name" {
  description = "The name of the database instance"
  value       = "${module.mysql-db.instance_name}"
}

**Comment by aaron-lane** [comment]
Hi @sagivle. Thank you for your interest in the project! I apologize for the extreme delay in responding. 

Do you have the output from a `terraform apply` which you can share?

**Comment by aaron-lane** [comment]
@sagivle please reopen this issue if you can provide more details.
