### ISSUE TITLE
Update variables

### ISSUE THREAD

**Issue by skinlayers** [terraform-google-modules/terraform-google-sql-db#9]
availability_type, crash_safe_replication, and user_labels need to be added.

**Comment by skinlayers** [comment]
Looks like this commit finally add the option. Could you please tag a new release? I've been waiting 11 months for this fix.

**Comment by BastienM** [comment]
You can add `project_id` and `zone` to the list.

The docs and examples shows `project_id` for the **v.1.1.1**([examples/mysql-and-postgres/main.tf](https://github.com/GoogleCloudPlatform/terraform-google-sql-db/blob/1.1.1/examples/mysql-and-postgres/main.tf#L68)) while still being named `project` behind the scene.

Seems to be the same with `zone`.

Tried the sources from registry.terraform.io and directly via git.

**Comment by skinlayers** [comment]
And you may want to attempt more atomic commits in the future. Waiting a year for simple patch (that I supplied in https://github.com/GoogleCloudPlatform/terraform-google-sql-db/pull/7) is a problem.

**Comment by skinlayers** [comment]
@danisla ^

**Comment by morgante** [comment]
@skinlayers Is there an issue with using the [postgres module](https://github.com/GoogleCloudPlatform/terraform-google-sql-db/tree/master/modules/postgresql)?
