### ISSUE TITLE
Add module_depends_on resource to private_service_access

### ISSUE THREAD

**Issue by hronix** [terraform-google-modules/terraform-google-sql-db#90]
- `private_service_access` module depends on *Service Networking API* and `vpc_network`, so it would be very helpful to have **module_depends_on** in `private_service_access`. 
- Also description for `private_service_access` should be updated, it useful not only for MySQL but also for Postgres databases.

**Comment by morgante** [comment]
Thanks for the suggestion, these both sound like reasonable additions/fixes.
